### PR TITLE
Rebuild image for verifying Prow

### PR DESCRIPTION
**Pull request by Anxhela21**
Signed-off-by: Anxhela <acoba@redhat.com>

* [x] lint,
* [x] unit-test,
* [ ] end-to-end test (if present), runs with the latest commits
* [x] push PR image to quay (pr-image-mirror), Yes, with tag: `2.4.0-PR149-09348d67af0547395a002256b3feb2aa82eba109`
* [x] push to main,
* [x] fast-forward to 2.4

 Other checks:

* [x] DCO sign-off check present
* [x] Changes are fast-forwarded to current release branch (2.4)
* [x] Changes are not fast-forwarded to previous release branch (2.3)

### CODE REVIEW

**Comment by mqhackett** [comment]
I still haven't gotten the hang of getting the tide check approval via slash commands, but this all looks good. Thanks!

**Comment by SherinV** [comment]
> I still haven't gotten the hang of getting the tide check approval via slash commands, but this all looks good. Thanks!

I think it needs approval from code owners to merge.

**Pull request merged**
